# Generated by Django 4.2.21 on 2025-06-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCabang',
            fields=[
                ('cabang_id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DimPelanggan',
            fields=[
                ('pelanggan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_type', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DimPembayaran',
            fields=[
                ('pembayaran_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DimProduk',
            fields=[
                ('produk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_line', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DimWaktu',
            fields=[
                ('tanggal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('hari', models.CharField(max_length=10)),
                ('bulan', models.CharField(max_length=10)),
                ('tahun', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FactPerformaProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimcabang')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimpelanggan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimproduk')),
                ('tanggal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimwaktu')),
            ],
        ),
        migrations.CreateModel(
            name='FactPenjualanCabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimcabang')),
                ('pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimpembayaran')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimproduk')),
                ('tanggal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimwaktu')),
            ],
        ),
        migrations.CreateModel(
            name='FactPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimcabang')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimpelanggan')),
                ('pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimpembayaran')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimproduk')),
                ('tanggal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olap.dimwaktu')),
            ],
        ),
    ]
